{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "dnt": "1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-39600000; XSRF-TOKEN=rvuhu0qs7lge7jeun0n3f897eu; JWT-SESSION=eyJhbGciOiJIUzI1NiJ9.eyJsYXN0UmVmcmVzaFRpbWUiOjE2MDUwMDk4Njg0MDksInhzcmZUb2tlbiI6InJ2dWh1MHFzN2xnZTdqZXVuMG4zZjg5N2V1IiwianRpIjoiQVhXd0hvWDBMTDVVZkUtdXZNTjkiLCJzdWIiOiJBWFdiX0hEcEtsX0ZGaEtuNzhmNSIsImlhdCI6MTYwNDk3NzU5MSwiZXhwIjoxNjA1MjY5MDY4fQ.5LauIitHbQsLgPV0y9drQgiNeDX7gcKrk5-zvMLnJ90; JSESSIONID.9f5c13a4=node01odugmestiqqf1tluzznzcbf1w1.node0; screenResolution=1440x900"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/synchronizeUsers",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/synchronizeUsers",
  "listenerPath": "/api/*",
  "relativePath": "/api/synchronizeUsers",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/synchronizeUsers",
  "rawRequestPath": "/api/synchronizeUsers",
  "remoteAddress": "/127.0.0.1:62770",
  "requestPath": "/api/synchronizeUsers"
}