{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "cache-control": "max-age=0",
    "dnt": "1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cookie": "jenkins-timestamper-offset=-39600000; XSRF-TOKEN=cra259717a1ubsu1uq9sr30qbq; JWT-SESSION=eyJhbGciOiJIUzI1NiJ9.eyJsYXN0UmVmcmVzaFRpbWUiOjE2MDUwODIxOTM3NjQsInhzcmZUb2tlbiI6ImNyYTI1OTcxN2ExdWJzdTF1cTlzcjMwcWJxIiwianRpIjoiQVhXMWx0MkNWZVdtMjVrZlhwV2MiLCJzdWIiOiJBWFdiX0hEcEtsX0ZGaEtuNzhmNSIsImlhdCI6MTYwNTA2OTM2NCwiZXhwIjoxNjA1MzQxMzkzfQ.dWE6KTLoimu7u2LitFv3Btd9LFBA85pnWJ12JYeZZPo"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/console/",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/",
  "listenerPath": "/console/*",
  "relativePath": "/console/",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/console/",
  "rawRequestPath": "/console/",
  "remoteAddress": "/127.0.0.1:50712",
  "requestPath": "/console/"
}