#%RAML 1.0 DataType

type: object
properties:
  errorDescription:
    description: Error details
    type: string
    example: "Failed to connect to database"

  errorType:   
    description: deails of error type 
    type: string
    example: "DB:CONNECTIVITY"